services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  uptime_kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      - VIRTUAL_HOST=${FQDN}
      - LETSENCRYPT_HOST=${FQDN}
      - LETSENCRYPT_MAIL=${EMAIL}
    volumes:
      - uptime-kuma-data:/app/data 
    security_opt:
      - no-new-privileges:true
    depends_on:
      - nginx-proxy
      - letsencrypt

volumes:
 uptime-kuma-data:
 vhostd:
 html:
 certs:
